### PR TITLE
Move TLS auxiliary test scripts to the framework

### LINKED ISSUE #54: Move TLS auxiliary test scripts to the framework
The following files are used on the CI, shared between branches on Mbed TLS (at the time of writing identical between branches) and should be moved to the framework:
- [x] `generate_ssl_debug_helpers.py` - used in CMake, Make, `tests/scripts/check-generated-files.sh` and `scripts/make_generated_files.bat`
- [x] `generate_tls13_compat_tests.py` - used in CMake, Make, `tests/scripts/check-generated-files.sh` and `scripts/make_generated_files.bat`
- [x] `translate_ciphers.py` - used in `compat.sh` and`tests/scripts/components-basic-checks.sh`.

For each file moved to the framework, adapt the path in all files that use it.

Note: these files are only used by `mbedtls` and won't be used by `tf-psa-crypto`, so there's no need to adapt to that repo, or worry about path differences.

### PR DESCRIPTION
**Pull request by eleuzi01**
Resolves #54 

Development PR: https://github.com/Mbed-TLS/mbedtls/pull/9673

### CODE REVIEW

**Comment by mpg** [comment]
Unfortunately we now have a conflict. Other than that, looks good to me at https://github.com/Mbed-TLS/mbedtls-framework/pull/56/commits/07d3d13380a9122d36fdad104813e93347c7b64b

**Comment by mpg** [comment]
I'm not exactly sure what the conflict is; it might be an artefact of how the script works - perhaps git sees this file added-then-removed by another branch that imported other files (and as a consequence, technically imported all the files and removed those that the other branch didn't want).

Considering git is not good at rebasing branches that have merge commits in their history, as is the case here, I'd suggest the easiest way to resolve this conflict would probably be to just merge the `main` branch back into this PR's branch.

**Comment by gilles-peskine-arm** [comment]
> I'm not exactly sure what the conflict is; it might be an artefact of how the script works - perhaps git sees this file added-then-removed by another branch that imported other files (and as a consequence, technically imported all the files and removed those that the other branch didn't want).

Indeed. When I try the merge locally I see a lot of modify/delete conflicts (reported as rename/delete for files that were moved to `tf-psa-crypto`). Which makes sense: as you say one branch modifies the file while the other one removes it, and git has no reason to know which one is right. I actually wonder how the version/configuration of git used on GitHub decides that only one file is problematic.

> Considering git is not good at rebasing branches that have merge commits in their history, as is the case here, I'd suggest the easiest way to resolve this conflict would probably be to just merge the main branch back into this PR's branch.

I don't have any hopes for `git rebase`. Re-running the move-to-framework script and cherry-picking the subsequent commits would be an option to get a cleaner history. Merging would be fine if we can make a meaningful merge commit, but I'm not sure how it would look like.

I guess this is a problem that's going to come up again — we can't easily do file moves in parallel.

**Comment by mpg** [comment]
> I actually wonder how the version/configuration of git used on GitHub decides that only one file is problematic.

The file indicated as problematic here is the only one that was modified (removing a `import framework_scripts_path # pylint: disable=unused-import` that was no longer needed), so I think that's why it's flagged. git is probably smart enough to figure out that the others had identical contents at the various points in the history where they were being deleting and not complain about them.

**Comment by gilles-peskine-arm** [comment]
> When I try the merge locally I see a lot of modify/delete conflicts (reported as rename/delete for files that were moved to tf-psa-crypto).

That was with git 2.34.1. With git 2.43.0 the only conflicts are
```
CONFLICT (rename/delete): tests/scripts/generate_tls13_compat_tests.py renamed to scripts/generate_tls13_compat_tests.py in HEAD, but deleted in main.
CONFLICT (modify/delete): scripts/generate_tls13_compat_tests.py deleted in main and modified in HEAD.  Version HEAD of scripts/generate_tls13_compat_tests.py left in tree.
CONFLICT (rename/delete): tests/scripts/check_test_cases.py renamed to scripts/mbedtls_framework/collect_test_cases.py in main, but deleted in HEAD.
CONFLICT (modify/delete): scripts/mbedtls_framework/collect_test_cases.py deleted in HEAD and modified in main.  Version main of scripts/mbedtls_framework/collect_test_cases.py left in tree.
```

I guess newer versions of git are more clever. Strategy options might matter, I haven't tried fiddling with them.

**Comment by gilles-peskine-arm** [comment]
> When I try the merge locally

Another difference between me and GitHub is that I was merging `main` into this branch. In complicated cases like this the conflicts might not be symmetrical.

**Comment by davidhorstmann-arm** [comment]
> Re-running the move-to-framework script and cherry-picking the subsequent commits would be an option to get a cleaner history.

This is what I've been doing when merge conflicts appear. At one time I considered trying to make a 'rebase' feature in the script to make this easier, but it's not much more difficult to just re-run the script to regenerate the move commit.

**Review by mpg — APPROVED** [review]
LGTM, thanks!

**Review by mpg — APPROVED** [review]

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM, thanks!

**Comment by davidhorstmann-arm** [comment]
CI on Mbed-TLS/mbedtls#9673 and Mbed-TLS/mbedtls#9675 validates this PR so I'll merge.

**Pull request merged**
