### PR TITLE
Fix generation of PSA test wrappers for PAKE

### PR DESCRIPTION
**Pull request by ronald-cron-arm**
Associated to https://github.com/Mbed-TLS/mbedtls/pull/9185

### CODE REVIEW

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM, thanks!

**Comment by davidhorstmann-arm** [comment]
Looks like this will need a force-push for DCO:
```
git commit --amend --no-edit
git push --force-with-lease
```

**Comment by ronald-cron-arm** [comment]
> Looks like this will need a force-push to retrigger DCO:
> 
> ```
> git commit --amend --no-edit
> git push --force-with-lease
> ```

Fixed.

**Review by tom-daubney-arm — APPROVED** [review]
LGTM - thanks

**Comment by tom-daubney-arm** [comment]
Just confirming my approval for the PR given the updates: LGTM.

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM for new changes as well

**Comment by ronald-cron-arm** [comment]
Validated for development with PR 9185 CI, for 3.6 with PR 9289 CI, 2 approvals, thus merging.

**Pull request merged**
